### ISSUE TITLE
CardDAV syncing of LDAP-backed users returning 405 error on OC8

### ISSUE THREAD

**Issue by logomancer** [owncloud/contacts#814]
Since upgrading from 7.0.4 to 8.0.0, I've been having some difficulty with CardDAV syncing with a user backed by LDAP. Every time I try, the server gives a 405 error. Syncing with a normal DB-backed user works normally. Also of interest: Sync adapters previously set up with LDAP users can't sync contacts, reporting 404 errors. It's like the contact stores aren't there anymore, but I can access them via the web interface.

**System Details**
Ubuntu 14.04
Apache 2.4.7
PHP 5.5.9
MySQL 5.5.41
Owncloud 8.0.0-7
Contacts App 0.3.0.18
Using DAVDroid 0.6.11 to sync

**Comment by minneyar** [comment]
I'm having the same problem; this is happening with both CalDAV and CardDAV.  I put more details in the calendar issue tracker at https://github.com/owncloud/calendar/issues/712.

**Comment by babelouest** [comment]
@jbtbnl , do you have an idea ? I have the same problem on my dev instance, CardDAV isn't accessible anymore since owncloud 8.

**Comment by jbtbnl** [comment]
Does it only occur with a LDAP setup?

**Comment by babelouest** [comment]
No, on my side it occurs on both database and ldap backend.

I have the following error message when I try to access the addressbook CardDAV url:
`User did not have the required privileges ({DAV:}read) for path "addressbooks/user/contacts"`

**Comment by Hydrael** [comment]
I have the same problem.
One thing I might be able to add:
I have set up my LDAP environment a while after I deployed owncloud on my server. To be able to keep my users data associated with their accounts (because their user names changed after migration to LDAP authentication) I manually updated the `oc_ldap_user_mapping` table pointing the `ldap_dn` to the internal `owncloud_name`.

This had worked with OC7.

**Comment by RealRancor** [comment]
Hi,

there is a longer thread about this issue available at the core tracker: https://github.com/owncloud/core/issues/14048 where currently a lot of people posting stuff rather than in here.

**Comment by lennartjuette** [comment]
I still have this issue with a fresh install of 8.0.2 (sqlite backend). I can't acces my calendar at https://example.org/owncloud/remote.php/carddav/addressbooks/test/kontakte.

Error:
```
<d:error>
<s:exception>Sabre\DAVACL\Exception\NeedPrivileges</s:exception>
<s:message>User did not have the required privileges ({DAV:}read) for path "addressbooks/test/kontakte"</s:message>
<s:sabredav-version>1.8.12</s:sabredav-version>
<d:need-privileges>
<d:resource>
<d:href>/owncloud/remote.php/carddav/addressbooks/test/kontakte</d:href>
<d:privilege>
<d:read/>
</d:privilege>
</d:resource>
</d:need-privileges>
</d:error>
```

Anything i can do to help?

**Comment by johnwoltman** [comment]
I am also experiencing the same issue with CardDAV and CalDAV.  See my comment here https://github.com/owncloud/calendar/issues/776#issuecomment-94630416

**Comment by childnode** [comment]
same as for https://github.com/owncloud/calendar/issues/782#issuecomment-105616927

Why are you bothering about GET request / responsed on a DAV endpoint that isn't designed to accept GET requests?

have a look at PROPFIND and REPORT requests http://sabre.io/dav/building-a-carddav-client/ 

What is wrong to me there:
```
<d:response>
  <d:href>/remote.php/carddav/addressbooks/marcel/kontakte</d:href>
  <d:propstat>
    <d:prop>
      <d:getlastmodified/>
      <d:getcontentlength/>
      <d:resourcetype/>
      <d:quota-used-bytes/>
      <d:quota-available-bytes/>
      <d:getetag/>
      <d:getcontenttype/>
    </d:prop>
    <d:status>HTTP/1.1 403 Forbidden</d:status>
  </d:propstat>
</d:response>
```

followed by MANY vcf entries like 
`/remote.php/carddav/addressbooks/marcel/kontakte/137755f1-8973-4a11-8d34-8d6262dd614f%2540owncloud.childno.de.vcf`
which should be accessible by GET but it isn't.

While complete list / VCF of alle elements is correctly returned by REPORT.

shoudn't anyone be 200 OK?

What I even don't understand: why is the GET readable content of a vcf empty?

even cardDav is not defined to respond to GET requests but PROPFIND too
(see https://tools.ietf.org/html/rfc6352 || http://sabre.io/dav/building-a-carddav-client/ )

anyway ... somehow it's working for me on DavDroid 0.77 but NOT on a Mac OSX 10.9
https://doc.owncloud.org/server/4.5/user_manual/sync_osx.html doesn't apply and always asks me for my password is prompted anytime I open account settings because it "is wrong" (sure, it's not). Contacts.app is empty.

**Comment by lennartjuette** [comment]
I retried everything in the last hour. It works. What has changed? I did use the most current version of Thunderbird/Lightning on a new machine, instead of using my 3 or. 4 weeks old release on another machine. It also works on my Android phone with CalDavSync

But there's still a problem with Mac OS X 10.6's iCal: Adding a calendar won't work here. The problem seems to be the client, since it tries to issue GET commands. GET worked on owncloud 7, it's not working on OC8 anymore.

Maybe SabreDAVs interface has been aligned with it's specification between OC 7 and OC 8?

I hav to test with a more current version of iCal, as soon as i have access to my own machine.

**Comment by childnode** [comment]
yes @lennartjuette seems to there were changes in 7 to 8. At the moment, I can't even reproduce the strange Forbidden errors anymore on 8.1. But nontheless, I get new one ;/

**Comment by babelouest** [comment]
@lennartjuette , @childnode , I made this connector a couple of years ago but never had the time to finish it and since then, OC has change its backend and the technical debt has grown.

I was able to fix some bugs so the sync is now possible, but there still are 2 problems I wasn't able to fix yet:
- Profile pictures: it's no longer possible to have profile pictures in a ldap backend. The format seems to have change
- Categories: this goes for a long time, even if the ldap entry 'o' or 'ou' is translated into a `CATEGORY`, it's not managed as a group in owncloud

@jbtbnl , do you have ideas on how to fix those 2 problems ? I guess it comes from unproper use of owncloud api but I have no clue on how to fix it...

**Comment by babelouest** [comment]
see #996 for ongoing fixes of ldap backend
